#!/bin/bash
if [ $# -ne 0 ];
then
  echo "usage: calculator"
  echo "   This runs a command-line calculator for calculating expressions"
  echo "   as an example of how a parser and parser actions can be used to"
  echo "   evaluate expressions as they are typed."
  exit
fi
python3 calculator.py
