#!/bin/bash
if [ $# -ne 1 ];
then
  echo "usage: classexample filename"
  echo "   Compiles or interprets filename as a program from the classexample language."
  echo "   Read the gencomp documentation found in gencomp for a description of "
  echo "   of a gencomp language description file."
  exit
fi
python3 classexample.py $1
