#!/bin/bash
if [ $# -ne 1 ];
then
  echo "usage: identifiers filename"
  echo "   Compiles or interprets filename as a program from the identifiers language."
  echo "   Read the gencomp documentation found in gencomp for a description of "
  echo "   of a gencomp language description file."
  exit
fi
python3 identifiers.py $1
