#!/bin/bash
if [ $# -ne 1 ];
then
  echo "usage: listexp filename"
  echo "   Compiles or interprets filename as a program from the listexp language."
  echo "   Read the gencomp documentation found in gencomp for a description of "
  echo "   of a gencomp language description file."
  exit
fi
python3 listexp.py $1
